package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA



/**
 * SweCompXPfuncion generated by hbm2java
 */
public class SweCompXPfuncion  implements java.io.Serializable {


     private SweCompXPfuncionId id;
     private SweCataDetret sweCataDetretByIdRetftr;
     private SweCataDetret sweCataDetretByIdDet;
     private SweCata sweCata;

    public SweCompXPfuncion() {
    }

    public SweCompXPfuncion(SweCompXPfuncionId id, SweCataDetret sweCataDetretByIdRetftr, SweCataDetret sweCataDetretByIdDet, SweCata sweCata) {
       this.id = id;
       this.sweCataDetretByIdRetftr = sweCataDetretByIdRetftr;
       this.sweCataDetretByIdDet = sweCataDetretByIdDet;
       this.sweCata = sweCata;
    }
   
    public SweCompXPfuncionId getId() {
        return this.id;
    }
    
    public void setId(SweCompXPfuncionId id) {
        this.id = id;
    }
    public SweCataDetret getSweCataDetretByIdRetftr() {
        return this.sweCataDetretByIdRetftr;
    }
    
    public void setSweCataDetretByIdRetftr(SweCataDetret sweCataDetretByIdRetftr) {
        this.sweCataDetretByIdRetftr = sweCataDetretByIdRetftr;
    }
    public SweCataDetret getSweCataDetretByIdDet() {
        return this.sweCataDetretByIdDet;
    }
    
    public void setSweCataDetretByIdDet(SweCataDetret sweCataDetretByIdDet) {
        this.sweCataDetretByIdDet = sweCataDetretByIdDet;
    }
    public SweCata getSweCata() {
        return this.sweCata;
    }
    
    public void setSweCata(SweCata sweCata) {
        this.sweCata = sweCata;
    }




}


