package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SweCataDetret generated by hbm2java
 */
public class SweCataDetret  implements java.io.Serializable {


     private int idcatalogoDetret;
     private SweTipoDetret sweTipoDetret;
     private SweCata sweCata;
     private int rangoInicial;
     private Integer rangoFinal;
     private Set sweCompXPfuncionsForIdDet = new HashSet(0);
     private Set sweCompXPfuncionsForIdRetftr = new HashSet(0);

    public SweCataDetret() {
    }

	
    public SweCataDetret(int idcatalogoDetret, SweTipoDetret sweTipoDetret, SweCata sweCata, int rangoInicial) {
        this.idcatalogoDetret = idcatalogoDetret;
        this.sweTipoDetret = sweTipoDetret;
        this.sweCata = sweCata;
        this.rangoInicial = rangoInicial;
    }
    public SweCataDetret(int idcatalogoDetret, SweTipoDetret sweTipoDetret, SweCata sweCata, int rangoInicial, Integer rangoFinal, Set sweCompXPfuncionsForIdDet, Set sweCompXPfuncionsForIdRetftr) {
       this.idcatalogoDetret = idcatalogoDetret;
       this.sweTipoDetret = sweTipoDetret;
       this.sweCata = sweCata;
       this.rangoInicial = rangoInicial;
       this.rangoFinal = rangoFinal;
       this.sweCompXPfuncionsForIdDet = sweCompXPfuncionsForIdDet;
       this.sweCompXPfuncionsForIdRetftr = sweCompXPfuncionsForIdRetftr;
    }
   
    public int getIdcatalogoDetret() {
        return this.idcatalogoDetret;
    }
    
    public void setIdcatalogoDetret(int idcatalogoDetret) {
        this.idcatalogoDetret = idcatalogoDetret;
    }
    public SweTipoDetret getSweTipoDetret() {
        return this.sweTipoDetret;
    }
    
    public void setSweTipoDetret(SweTipoDetret sweTipoDetret) {
        this.sweTipoDetret = sweTipoDetret;
    }
    public SweCata getSweCata() {
        return this.sweCata;
    }
    
    public void setSweCata(SweCata sweCata) {
        this.sweCata = sweCata;
    }
    public int getRangoInicial() {
        return this.rangoInicial;
    }
    
    public void setRangoInicial(int rangoInicial) {
        this.rangoInicial = rangoInicial;
    }
    public Integer getRangoFinal() {
        return this.rangoFinal;
    }
    
    public void setRangoFinal(Integer rangoFinal) {
        this.rangoFinal = rangoFinal;
    }
    public Set getSweCompXPfuncionsForIdDet() {
        return this.sweCompXPfuncionsForIdDet;
    }
    
    public void setSweCompXPfuncionsForIdDet(Set sweCompXPfuncionsForIdDet) {
        this.sweCompXPfuncionsForIdDet = sweCompXPfuncionsForIdDet;
    }
    public Set getSweCompXPfuncionsForIdRetftr() {
        return this.sweCompXPfuncionsForIdRetftr;
    }
    
    public void setSweCompXPfuncionsForIdRetftr(Set sweCompXPfuncionsForIdRetftr) {
        this.sweCompXPfuncionsForIdRetftr = sweCompXPfuncionsForIdRetftr;
    }




}


