package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA



/**
 * SweCompXPfuncionId generated by hbm2java
 */
public class SweCompXPfuncionId  implements java.io.Serializable {


     private int idDet;
     private int idRetftr;
     private int idCatcomplejidad;

    public SweCompXPfuncionId() {
    }

    public SweCompXPfuncionId(int idDet, int idRetftr, int idCatcomplejidad) {
       this.idDet = idDet;
       this.idRetftr = idRetftr;
       this.idCatcomplejidad = idCatcomplejidad;
    }
   
    public int getIdDet() {
        return this.idDet;
    }
    
    public void setIdDet(int idDet) {
        this.idDet = idDet;
    }
    public int getIdRetftr() {
        return this.idRetftr;
    }
    
    public void setIdRetftr(int idRetftr) {
        this.idRetftr = idRetftr;
    }
    public int getIdCatcomplejidad() {
        return this.idCatcomplejidad;
    }
    
    public void setIdCatcomplejidad(int idCatcomplejidad) {
        this.idCatcomplejidad = idCatcomplejidad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SweCompXPfuncionId) ) return false;
		 SweCompXPfuncionId castOther = ( SweCompXPfuncionId ) other; 
         
		 return (this.getIdDet()==castOther.getIdDet())
 && (this.getIdRetftr()==castOther.getIdRetftr())
 && (this.getIdCatcomplejidad()==castOther.getIdCatcomplejidad());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDet();
         result = 37 * result + this.getIdRetftr();
         result = 37 * result + this.getIdCatcomplejidad();
         return result;
   }   


}


