package com.amerika.swe.model;
// Generated 16/10/2013 08:47:53 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SweCata generated by hbm2java
 */
public class SweCata  implements java.io.Serializable {


     private int idCatalogo;
     private SweTipoCata sweTipoCata;
     private String nombre;
     private String descripcion;
     private String estado;
     private BigDecimal valor;
     private Set sweTipoApliXFtecsForCodigoFacttecnico = new HashSet(0);
     private Set sweHomoXetapas = new HashSet(0);
     private Set sweSolisForIdLenguaje = new HashSet(0);
     private Set sweSolisForIdPerfil = new HashSet(0);
     private Set sweSolisForIdTposolicitud = new HashSet(0);
     private Set sweDefperfAsociahrXlengsForIdLenguaje = new HashSet(0);
     private Set sweSolisForIdAplicacion = new HashSet(0);
     private Set sweDefperfAsociahrXlengsForIdPerfil = new HashSet(0);
     private Set sweSolisForIdEstado = new HashSet(0);
     private Set sweTipoApliXFtecsForCodigoTpoaplicacion = new HashSet(0);
     private Set sweCompXsolisForIdComplejidad = new HashSet(0);
     private Set sweCompXsolisForIdTpocomponente = new HashSet(0);
     private Set sweEtapaXsols = new HashSet(0);
     private Set sweFtecnXsols = new HashSet(0);
     private Set sweTcompXCompsForIdTpocomplejidad = new HashSet(0);
     private Set sweCataDetrets = new HashSet(0);
     private Set sweFactAmbiXsols = new HashSet(0);
     private Set swePorcDistXetapas = new HashSet(0);
     private Set sweTcompXCompsForIdTpocomponente = new HashSet(0);
     private Set sweCompXPfuncions = new HashSet(0);
     private Set sweFactCalXTsols = new HashSet(0);
     private Set sweIntervalosForIdLenguaje = new HashSet(0);
     private Set sweIntervalosForIdPerfil = new HashSet(0);        
     
    public SweCata() {
    }

	
    public SweCata(int idCatalogo, SweTipoCata sweTipoCata, String nombre, String descripcion) {
        this.idCatalogo = idCatalogo;
        this.sweTipoCata = sweTipoCata;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public SweCata(int idCatalogo, SweTipoCata sweTipoCata, String nombre, String descripcion, String estado, BigDecimal valor, Set sweTipoApliXFtecsForCodigoFacttecnico, Set sweHomoXetapas, Set sweSolisForIdLenguaje, Set sweSolisForIdPerfil, Set sweSolisForIdTposolicitud, Set sweDefperfAsociahrXlengsForIdLenguaje, Set sweSolisForIdAplicacion, Set sweDefperfAsociahrXlengsForIdPerfil, Set sweSolisForIdEstado, Set sweTipoApliXFtecsForCodigoTpoaplicacion, Set sweCompXsolisForIdComplejidad, Set sweCompXsolisForIdTpocomponente, Set sweEtapaXsols, Set sweFtecnXsols, Set sweTcompXCompsForIdTpocomplejidad, Set sweCataDetrets, Set sweFactAmbiXsols, Set swePorcDistXetapas, Set sweTcompXCompsForIdTpocomponente, Set sweCompXPfuncions, Set sweFactCalXTsols, Set sweIntervalosForIdLenguaje, Set sweIntervalosForIdPerfil) {
       this.idCatalogo = idCatalogo;
       this.sweTipoCata = sweTipoCata;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.valor = valor;
       this.sweTipoApliXFtecsForCodigoFacttecnico = sweTipoApliXFtecsForCodigoFacttecnico;
       this.sweHomoXetapas = sweHomoXetapas;
       this.sweSolisForIdLenguaje = sweSolisForIdLenguaje;
       this.sweSolisForIdPerfil = sweSolisForIdPerfil;
       this.sweSolisForIdTposolicitud = sweSolisForIdTposolicitud;
       this.sweDefperfAsociahrXlengsForIdLenguaje = sweDefperfAsociahrXlengsForIdLenguaje;
       this.sweSolisForIdAplicacion = sweSolisForIdAplicacion;
       this.sweDefperfAsociahrXlengsForIdPerfil = sweDefperfAsociahrXlengsForIdPerfil;
       this.sweSolisForIdEstado = sweSolisForIdEstado;
       this.sweTipoApliXFtecsForCodigoTpoaplicacion = sweTipoApliXFtecsForCodigoTpoaplicacion;
       this.sweCompXsolisForIdComplejidad = sweCompXsolisForIdComplejidad;
       this.sweCompXsolisForIdTpocomponente = sweCompXsolisForIdTpocomponente;
       this.sweEtapaXsols = sweEtapaXsols;
       this.sweFtecnXsols = sweFtecnXsols;
       this.sweTcompXCompsForIdTpocomplejidad = sweTcompXCompsForIdTpocomplejidad;
       this.sweCataDetrets = sweCataDetrets;
       this.sweFactAmbiXsols = sweFactAmbiXsols;
       this.swePorcDistXetapas = swePorcDistXetapas;
       this.sweTcompXCompsForIdTpocomponente = sweTcompXCompsForIdTpocomponente;
       this.sweCompXPfuncions = sweCompXPfuncions;
       this.sweFactCalXTsols = sweFactCalXTsols;
       this.sweIntervalosForIdLenguaje = sweIntervalosForIdLenguaje;
       this.sweIntervalosForIdPerfil = sweIntervalosForIdPerfil;
    }
   
    public int getIdCatalogo() {
        return this.idCatalogo;
    }
    
    public void setIdCatalogo(int idCatalogo) {
        this.idCatalogo = idCatalogo;
    }
    public SweTipoCata getSweTipoCata() {
        return this.sweTipoCata;
    }
    
    public void setSweTipoCata(SweTipoCata sweTipoCata) {
        this.sweTipoCata = sweTipoCata;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Set getSweTipoApliXFtecsForCodigoFacttecnico() {
        return this.sweTipoApliXFtecsForCodigoFacttecnico;
    }
    
    public void setSweTipoApliXFtecsForCodigoFacttecnico(Set sweTipoApliXFtecsForCodigoFacttecnico) {
        this.sweTipoApliXFtecsForCodigoFacttecnico = sweTipoApliXFtecsForCodigoFacttecnico;
    }
    public Set getSweHomoXetapas() {
        return this.sweHomoXetapas;
    }
    
    public void setSweHomoXetapas(Set sweHomoXetapas) {
        this.sweHomoXetapas = sweHomoXetapas;
    }
    public Set getSweSolisForIdLenguaje() {
        return this.sweSolisForIdLenguaje;
    }
    
    public void setSweSolisForIdLenguaje(Set sweSolisForIdLenguaje) {
        this.sweSolisForIdLenguaje = sweSolisForIdLenguaje;
    }
    public Set getSweSolisForIdPerfil() {
        return this.sweSolisForIdPerfil;
    }
    
    public void setSweSolisForIdPerfil(Set sweSolisForIdPerfil) {
        this.sweSolisForIdPerfil = sweSolisForIdPerfil;
    }
    public Set getSweSolisForIdTposolicitud() {
        return this.sweSolisForIdTposolicitud;
    }
    
    public void setSweSolisForIdTposolicitud(Set sweSolisForIdTposolicitud) {
        this.sweSolisForIdTposolicitud = sweSolisForIdTposolicitud;
    }
    public Set getSweDefperfAsociahrXlengsForIdLenguaje() {
        return this.sweDefperfAsociahrXlengsForIdLenguaje;
    }
    
    public void setSweDefperfAsociahrXlengsForIdLenguaje(Set sweDefperfAsociahrXlengsForIdLenguaje) {
        this.sweDefperfAsociahrXlengsForIdLenguaje = sweDefperfAsociahrXlengsForIdLenguaje;
    }
    public Set getSweSolisForIdAplicacion() {
        return this.sweSolisForIdAplicacion;
    }
    
    public void setSweSolisForIdAplicacion(Set sweSolisForIdAplicacion) {
        this.sweSolisForIdAplicacion = sweSolisForIdAplicacion;
    }
    public Set getSweDefperfAsociahrXlengsForIdPerfil() {
        return this.sweDefperfAsociahrXlengsForIdPerfil;
    }
    
    public void setSweDefperfAsociahrXlengsForIdPerfil(Set sweDefperfAsociahrXlengsForIdPerfil) {
        this.sweDefperfAsociahrXlengsForIdPerfil = sweDefperfAsociahrXlengsForIdPerfil;
    }
    public Set getSweSolisForIdEstado() {
        return this.sweSolisForIdEstado;
    }
    
    public void setSweSolisForIdEstado(Set sweSolisForIdEstado) {
        this.sweSolisForIdEstado = sweSolisForIdEstado;
    }
    public Set getSweTipoApliXFtecsForCodigoTpoaplicacion() {
        return this.sweTipoApliXFtecsForCodigoTpoaplicacion;
    }
    
    public void setSweTipoApliXFtecsForCodigoTpoaplicacion(Set sweTipoApliXFtecsForCodigoTpoaplicacion) {
        this.sweTipoApliXFtecsForCodigoTpoaplicacion = sweTipoApliXFtecsForCodigoTpoaplicacion;
    }
    public Set getSweCompXsolisForIdComplejidad() {
        return this.sweCompXsolisForIdComplejidad;
    }
    
    public void setSweCompXsolisForIdComplejidad(Set sweCompXsolisForIdComplejidad) {
        this.sweCompXsolisForIdComplejidad = sweCompXsolisForIdComplejidad;
    }
    public Set getSweCompXsolisForIdTpocomponente() {
        return this.sweCompXsolisForIdTpocomponente;
    }
    
    public void setSweCompXsolisForIdTpocomponente(Set sweCompXsolisForIdTpocomponente) {
        this.sweCompXsolisForIdTpocomponente = sweCompXsolisForIdTpocomponente;
    }
    public Set getSweEtapaXsols() {
        return this.sweEtapaXsols;
    }
    
    public void setSweEtapaXsols(Set sweEtapaXsols) {
        this.sweEtapaXsols = sweEtapaXsols;
    }
    public Set getSweFtecnXsols() {
        return this.sweFtecnXsols;
    }
    
    public void setSweFtecnXsols(Set sweFtecnXsols) {
        this.sweFtecnXsols = sweFtecnXsols;
    }
    public Set getSweTcompXCompsForIdTpocomplejidad() {
        return this.sweTcompXCompsForIdTpocomplejidad;
    }
    
    public void setSweTcompXCompsForIdTpocomplejidad(Set sweTcompXCompsForIdTpocomplejidad) {
        this.sweTcompXCompsForIdTpocomplejidad = sweTcompXCompsForIdTpocomplejidad;
    }
    public Set getSweCataDetrets() {
        return this.sweCataDetrets;
    }
    
    public void setSweCataDetrets(Set sweCataDetrets) {
        this.sweCataDetrets = sweCataDetrets;
    }
    public Set getSweFactAmbiXsols() {
        return this.sweFactAmbiXsols;
    }
    
    public void setSweFactAmbiXsols(Set sweFactAmbiXsols) {
        this.sweFactAmbiXsols = sweFactAmbiXsols;
    }
    public Set getSwePorcDistXetapas() {
        return this.swePorcDistXetapas;
    }
    
    public void setSwePorcDistXetapas(Set swePorcDistXetapas) {
        this.swePorcDistXetapas = swePorcDistXetapas;
    }
    public Set getSweTcompXCompsForIdTpocomponente() {
        return this.sweTcompXCompsForIdTpocomponente;
    }
    
    public void setSweTcompXCompsForIdTpocomponente(Set sweTcompXCompsForIdTpocomponente) {
        this.sweTcompXCompsForIdTpocomponente = sweTcompXCompsForIdTpocomponente;
    }
    public Set getSweCompXPfuncions() {
        return this.sweCompXPfuncions;
    }
    
    public void setSweCompXPfuncions(Set sweCompXPfuncions) {
        this.sweCompXPfuncions = sweCompXPfuncions;
    }
    public Set getSweFactCalXTsols() {
        return this.sweFactCalXTsols;
    }
    
    public void setSweFactCalXTsols(Set sweFactCalXTsols) {
        this.sweFactCalXTsols = sweFactCalXTsols;
    }

    /**
     * @return the sweIntervalosForIdLenguaje
     */
    public Set getSweIntervalosForIdLenguaje() {
        return sweIntervalosForIdLenguaje;
    }

    /**
     * @param sweIntervalosForIdLenguaje the sweIntervalosForIdLenguaje to set
     */
    public void setSweIntervalosForIdLenguaje(Set sweIntervalosForIdLenguaje) {
        this.sweIntervalosForIdLenguaje = sweIntervalosForIdLenguaje;
    }

    /**
     * @return the sweIntervalosForIdPerfil
     */
    public Set getSweIntervalosForIdPerfil() {
        return sweIntervalosForIdPerfil;
    }

    /**
     * @param sweIntervalosForIdPerfil the sweIntervalosForIdPerfil to set
     */
    public void setSweIntervalosForIdPerfil(Set sweIntervalosForIdPerfil) {
        this.sweIntervalosForIdPerfil = sweIntervalosForIdPerfil;
    }




}


