package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * SweDefperfAsociahrXleng generated by hbm2java
 */
public class SweDefperfAsociahrXleng  implements java.io.Serializable {


     private int idPerfhrleng;
     private SweCata sweCataByIdLenguaje;
     private SweCata sweCataByIdPerfil;
     private BigDecimal horas;
     private Date vigenciaInicial;
     private Date vigenciaFinal;

    public SweDefperfAsociahrXleng() {
    }

	
    public SweDefperfAsociahrXleng(int idPerfhrleng, SweCata sweCataByIdLenguaje, SweCata sweCataByIdPerfil, BigDecimal horas, Date vigenciaInicial) {
        this.idPerfhrleng = idPerfhrleng;
        this.sweCataByIdLenguaje = sweCataByIdLenguaje;
        this.sweCataByIdPerfil = sweCataByIdPerfil;
        this.horas = horas;
        this.vigenciaInicial = vigenciaInicial;
    }
    public SweDefperfAsociahrXleng(int idPerfhrleng, SweCata sweCataByIdLenguaje, SweCata sweCataByIdPerfil, BigDecimal horas, Date vigenciaInicial, Date vigenciaFinal) {
       this.idPerfhrleng = idPerfhrleng;
       this.sweCataByIdLenguaje = sweCataByIdLenguaje;
       this.sweCataByIdPerfil = sweCataByIdPerfil;
       this.horas = horas;
       this.vigenciaInicial = vigenciaInicial;
       this.vigenciaFinal = vigenciaFinal;
    }
   
    public int getIdPerfhrleng() {
        return this.idPerfhrleng;
    }
    
    public void setIdPerfhrleng(int idPerfhrleng) {
        this.idPerfhrleng = idPerfhrleng;
    }
    public SweCata getSweCataByIdLenguaje() {
        return this.sweCataByIdLenguaje;
    }
    
    public void setSweCataByIdLenguaje(SweCata sweCataByIdLenguaje) {
        this.sweCataByIdLenguaje = sweCataByIdLenguaje;
    }
    public SweCata getSweCataByIdPerfil() {
        return this.sweCataByIdPerfil;
    }
    
    public void setSweCataByIdPerfil(SweCata sweCataByIdPerfil) {
        this.sweCataByIdPerfil = sweCataByIdPerfil;
    }
    public BigDecimal getHoras() {
        return this.horas;
    }
    
    public void setHoras(BigDecimal horas) {
        this.horas = horas;
    }
    public Date getVigenciaInicial() {
        return this.vigenciaInicial;
    }
    
    public void setVigenciaInicial(Date vigenciaInicial) {
        this.vigenciaInicial = vigenciaInicial;
    }
    public Date getVigenciaFinal() {
        return this.vigenciaFinal;
    }
    
    public void setVigenciaFinal(Date vigenciaFinal) {
        this.vigenciaFinal = vigenciaFinal;
    }


}


