package com.amerika.swe.model;
// Generated 18/10/2013 09:22:21 AM by Hibernate Tools 3.2.1.GA



/**
 * SweEtapaXsolId generated by hbm2java
 */
public class SweEtapaXsolId  implements java.io.Serializable {


     private int idEstimacion;
     private int codigoEtapa;

    public SweEtapaXsolId() {
    }

    public SweEtapaXsolId(int idEstimacion, int codigoEtapa) {
       this.idEstimacion = idEstimacion;
       this.codigoEtapa = codigoEtapa;
    }
   
    public int getIdEstimacion() {
        return this.idEstimacion;
    }
    
    public void setIdEstimacion(int idEstimacion) {
        this.idEstimacion = idEstimacion;
    }
    public int getCodigoEtapa() {
        return this.codigoEtapa;
    }
    
    public void setCodigoEtapa(int codigoEtapa) {
        this.codigoEtapa = codigoEtapa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SweEtapaXsolId) ) return false;
		 SweEtapaXsolId castOther = ( SweEtapaXsolId ) other; 
         
		 return (this.getIdEstimacion()==castOther.getIdEstimacion())
 && (this.getCodigoEtapa()==castOther.getCodigoEtapa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEstimacion();
         result = 37 * result + this.getCodigoEtapa();
         return result;
   }   


}


