package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * SweFactCalXTsol generated by hbm2java
 */
public class SweFactCalXTsol  implements java.io.Serializable {

     private int idFactcal;
     private SweCata sweCata;
     private BigDecimal valor;
     private Date vigenciaInicial;
     private Date vigenciaFinal;

    public SweFactCalXTsol() {
    }

    public SweFactCalXTsol(int idFactcal, SweCata sweCata, BigDecimal valor, Date vigenciaInicial) {
        this.idFactcal = idFactcal;
        this.sweCata = sweCata;
        this.valor = valor;
        this.vigenciaInicial = vigenciaInicial;
    }

    public SweFactCalXTsol(int idFactcal, SweCata sweCata, BigDecimal valor, Date vigenciaInicial, Date vigenciaFinal) {
       this.idFactcal = idFactcal;
       this.sweCata = sweCata;
       this.valor = valor;
       this.vigenciaInicial = vigenciaInicial;
       this.vigenciaFinal = vigenciaFinal;
    }

    public int getIdFactcal() {
        return this.idFactcal;
    }

    public void setIdFactcal(int idFactcal) {
        this.idFactcal = idFactcal;
    }

    public SweCata getSweCata() {
        return this.sweCata;
    }

    public void setSweCata(SweCata sweCata) {
        this.sweCata = sweCata;
    }

    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public Date getVigenciaInicial() {
        return this.vigenciaInicial;
    }

    public void setVigenciaInicial(Date vigenciaInicial) {
        this.vigenciaInicial = vigenciaInicial;
    }

    public Date getVigenciaFinal() {
        return this.vigenciaFinal;
    }

    public void setVigenciaFinal(Date vigenciaFinal) {
        this.vigenciaFinal = vigenciaFinal;
    }

}
