package com.amerika.swe.model;
// Generated 26/11/2013 01:46:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SweFuncionPerfil generated by hbm2java
 */
public class SweFuncionPerfil  implements java.io.Serializable {


     private SweFuncionPerfilId id;
     private SwePerfil swePerfil;
     private SweFuncion sweFuncion;
     private String usuario;
     private String programa;
     private Date fechaModif;

    public SweFuncionPerfil() {
    }

    public SweFuncionPerfil(SweFuncionPerfilId id, SwePerfil swePerfil, SweFuncion sweFuncion, String usuario, String programa, Date fechaModif) {
       this.id = id;
       this.swePerfil = swePerfil;
       this.sweFuncion = sweFuncion;
       this.usuario = usuario;
       this.programa = programa;
       this.fechaModif = fechaModif;
    }
   
    public SweFuncionPerfilId getId() {
        return this.id;
    }
    
    public void setId(SweFuncionPerfilId id) {
        this.id = id;
    }
    public SwePerfil getSwePerfil() {
        return this.swePerfil;
    }
    
    public void setSwePerfil(SwePerfil swePerfil) {
        this.swePerfil = swePerfil;
    }
    public SweFuncion getSweFuncion() {
        return this.sweFuncion;
    }
    
    public void setSweFuncion(SweFuncion sweFuncion) {
        this.sweFuncion = sweFuncion;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }




}


