package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA



/**
 * SweFtecnXsol generated by hbm2java
 */
public class SweFtecnXsol  implements java.io.Serializable {


     private SweFtecnXsolId id;
     private SweCata sweCata;
     private SweSoli sweSoli;
     private int gradoInfluencia;

    public SweFtecnXsol() {
    }

    public SweFtecnXsol(SweFtecnXsolId id, SweCata sweCata, SweSoli sweSoli, int gradoInfluencia) {
       this.id = id;
       this.sweCata = sweCata;
       this.sweSoli = sweSoli;
       this.gradoInfluencia = gradoInfluencia;
    }
   
    public SweFtecnXsolId getId() {
        return this.id;
    }
    
    public void setId(SweFtecnXsolId id) {
        this.id = id;
    }
    public SweCata getSweCata() {
        return this.sweCata;
    }
    
    public void setSweCata(SweCata sweCata) {
        this.sweCata = sweCata;
    }
    public SweSoli getSweSoli() {
        return this.sweSoli;
    }
    
    public void setSweSoli(SweSoli sweSoli) {
        this.sweSoli = sweSoli;
    }
    public int getGradoInfluencia() {
        return this.gradoInfluencia;
    }
    
    public void setGradoInfluencia(int gradoInfluencia) {
        this.gradoInfluencia = gradoInfluencia;
    }




}


