package com.amerika.swe.model;
// Generated 26/11/2013 01:46:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SweFuncion generated by hbm2java
 */
public class SweFuncion  implements java.io.Serializable {


     private int codigo;
     private String usuario;
     private String programa;
     private Date fechaModif;
     private String nombre;
     private Date fechaAlta;
     private Date fechaBaja;
     private String codigoTipo;
     private Set sweFuncionPerfils = new HashSet(0);

    public SweFuncion() {
    }

	
    public SweFuncion(int codigo, String usuario, String programa, Date fechaModif, String nombre, Date fechaAlta) {
        this.codigo = codigo;
        this.usuario = usuario;
        this.programa = programa;
        this.fechaModif = fechaModif;
        this.nombre = nombre;
        this.fechaAlta = fechaAlta;
    }
    public SweFuncion(int codigo, String usuario, String programa, Date fechaModif, String nombre, Date fechaAlta, Date fechaBaja, String codigoTipo, Set sweFuncionPerfils) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.programa = programa;
       this.fechaModif = fechaModif;
       this.nombre = nombre;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.codigoTipo = codigoTipo;
       this.sweFuncionPerfils = sweFuncionPerfils;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public String getCodigoTipo() {
        return this.codigoTipo;
    }
    
    public void setCodigoTipo(String codigoTipo) {
        this.codigoTipo = codigoTipo;
    }
    public Set getSweFuncionPerfils() {
        return this.sweFuncionPerfils;
    }
    
    public void setSweFuncionPerfils(Set sweFuncionPerfils) {
        this.sweFuncionPerfils = sweFuncionPerfils;
    }




}


