package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA



/**
 * SweHomoXetapa generated by hbm2java
 */
public class SweHomoXetapa  implements java.io.Serializable {


     private int idHomologxetapa;
     private SweCata sweCata;
     private String fase;

    public SweHomoXetapa() {
    }

    public SweHomoXetapa(int idHomologxetapa, SweCata sweCata, String fase) {
       this.idHomologxetapa = idHomologxetapa;
       this.sweCata = sweCata;
       this.fase = fase;
    }
   
    public int getIdHomologxetapa() {
        return this.idHomologxetapa;
    }
    
    public void setIdHomologxetapa(int idHomologxetapa) {
        this.idHomologxetapa = idHomologxetapa;
    }
    public SweCata getSweCata() {
        return this.sweCata;
    }
    
    public void setSweCata(SweCata sweCata) {
        this.sweCata = sweCata;
    }
    public String getFase() {
        return this.fase;
    }
    
    public void setFase(String fase) {
        this.fase = fase;
    }




}


