package com.amerika.swe.model;
// Generated 26/11/2013 01:46:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SweMenuPerfil generated by hbm2java
 */
public class SweMenuPerfil  implements java.io.Serializable {


     private SweMenuPerfilId id;
     private SwePerfil swePerfil;
     private SweMenu sweMenu;
     private String usuario;
     private String programa;
     private Date fechaModif;

    public SweMenuPerfil() {
    }

    public SweMenuPerfil(SweMenuPerfilId id, SwePerfil swePerfil, SweMenu sweMenu, String usuario, String programa, Date fechaModif) {
       this.id = id;
       this.swePerfil = swePerfil;
       this.sweMenu = sweMenu;
       this.usuario = usuario;
       this.programa = programa;
       this.fechaModif = fechaModif;
    }
   
    public SweMenuPerfilId getId() {
        return this.id;
    }
    
    public void setId(SweMenuPerfilId id) {
        this.id = id;
    }
    public SwePerfil getSwePerfil() {
        return this.swePerfil;
    }
    
    public void setSwePerfil(SwePerfil swePerfil) {
        this.swePerfil = swePerfil;
    }
    public SweMenu getSweMenu() {
        return this.sweMenu;
    }
    
    public void setSweMenu(SweMenu sweMenu) {
        this.sweMenu = sweMenu;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }




}


