package com.amerika.swe.model;
// Generated 26/11/2013 01:46:12 PM by Hibernate Tools 3.2.1.GA



/**
 * SweMenuPerfilId generated by hbm2java
 */
public class SweMenuPerfilId  implements java.io.Serializable {


     private int codigoMenu;
     private String codigoPerfil;

    public SweMenuPerfilId() {
    }

    public SweMenuPerfilId(int codigoMenu, String codigoPerfil) {
       this.codigoMenu = codigoMenu;
       this.codigoPerfil = codigoPerfil;
    }
   
    public int getCodigoMenu() {
        return this.codigoMenu;
    }
    
    public void setCodigoMenu(int codigoMenu) {
        this.codigoMenu = codigoMenu;
    }
    public String getCodigoPerfil() {
        return this.codigoPerfil;
    }
    
    public void setCodigoPerfil(String codigoPerfil) {
        this.codigoPerfil = codigoPerfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SweMenuPerfilId) ) return false;
		 SweMenuPerfilId castOther = ( SweMenuPerfilId ) other; 
         
		 return (this.getCodigoMenu()==castOther.getCodigoMenu())
 && ( (this.getCodigoPerfil()==castOther.getCodigoPerfil()) || ( this.getCodigoPerfil()!=null && castOther.getCodigoPerfil()!=null && this.getCodigoPerfil().equals(castOther.getCodigoPerfil()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoMenu();
         result = 37 * result + ( getCodigoPerfil() == null ? 0 : this.getCodigoPerfil().hashCode() );
         return result;
   }   


}


