package com.amerika.swe.model;
// Generated 26/11/2013 01:46:12 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SwePerfil generated by hbm2java
 */
public class SwePerfil  implements java.io.Serializable {


     private String codigo;
     private String usuario;
     private String programa;
     private Date fechaModif;
     private String nombre;
     private String estado;
     private Date fechaAlta;
     private Date fechaBaja;
     private Set sweMenuPerfils = new HashSet(0);
     private Set sweFuncionPerfils = new HashSet(0);
     private Set sweUsuarioPerfils = new HashSet(0);

    public SwePerfil() {
    }

	
    public SwePerfil(String codigo, String usuario, String programa, Date fechaModif, String nombre, String estado, Date fechaAlta) {
        this.codigo = codigo;
        this.usuario = usuario;
        this.programa = programa;
        this.fechaModif = fechaModif;
        this.nombre = nombre;
        this.estado = estado;
        this.fechaAlta = fechaAlta;
    }
    public SwePerfil(String codigo, String usuario, String programa, Date fechaModif, String nombre, String estado, Date fechaAlta, Date fechaBaja, Set sweMenuPerfils, Set sweFuncionPerfils, Set sweUsuarioPerfils) {
       this.codigo = codigo;
       this.usuario = usuario;
       this.programa = programa;
       this.fechaModif = fechaModif;
       this.nombre = nombre;
       this.estado = estado;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.sweMenuPerfils = sweMenuPerfils;
       this.sweFuncionPerfils = sweFuncionPerfils;
       this.sweUsuarioPerfils = sweUsuarioPerfils;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(String programa) {
        this.programa = programa;
    }
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getSweMenuPerfils() {
        return this.sweMenuPerfils;
    }
    
    public void setSweMenuPerfils(Set sweMenuPerfils) {
        this.sweMenuPerfils = sweMenuPerfils;
    }
    public Set getSweFuncionPerfils() {
        return this.sweFuncionPerfils;
    }
    
    public void setSweFuncionPerfils(Set sweFuncionPerfils) {
        this.sweFuncionPerfils = sweFuncionPerfils;
    }
    public Set getSweUsuarioPerfils() {
        return this.sweUsuarioPerfils;
    }
    
    public void setSweUsuarioPerfils(Set sweUsuarioPerfils) {
        this.sweUsuarioPerfils = sweUsuarioPerfils;
    }




}


