package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * SweParam generated by hbm2java
 */
public class SweParam  implements java.io.Serializable {


     private short codigoParam;
     private String nombre;
     private String descripcion;
     private String tipo;
     private BigDecimal valor;
     private Short longitud;

    public SweParam() {
    }

	
    public SweParam(short codigoParam, String nombre, String descripcion, String tipo, BigDecimal valor) {
        this.codigoParam = codigoParam;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.tipo = tipo;
        this.valor = valor;
    }
    public SweParam(short codigoParam, String nombre, String descripcion, String tipo, BigDecimal valor, Short longitud) {
       this.codigoParam = codigoParam;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.valor = valor;
       this.longitud = longitud;
    }
   
    public short getCodigoParam() {
        return this.codigoParam;
    }
    
    public void setCodigoParam(short codigoParam) {
        this.codigoParam = codigoParam;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Short getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Short longitud) {
        this.longitud = longitud;
    }




}


