package com.amerika.swe.model;
// Generated 18/10/2013 09:22:21 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SweSoli generated by hbm2java
 */
public class SweSoli  implements java.io.Serializable {

     private int idEstimacion;
     private SweCata sweCataByIdEstado;
     private SweCata sweCataByIdAplicacion;
     private SweCata sweCataByIdTposolicitud;
     private SweCata sweCataByIdLenguaje;
     private SweCata sweCataByIdPerfil;
     private int numSolicitud;
     private SweUsuarios sweUsuariosByIdUsu_estima;
     private SweUsuarios sweUsuariosByIdUsu_cierra;
     private String descripcion;
     private String aprobada;
     private Date fechaModificacion;
     private Date fechaAprobacion;
     private Date fechaCreacion;
     private BigDecimal upf;
     private BigDecimal vaf;
     private BigDecimal apf;
     private BigDecimal fce;
     private BigDecimal fcr;
     private BigDecimal he;
     private BigDecimal hr;
     private int ct;
     private BigDecimal tpf;
     private BigDecimal hepf;
     private BigDecimal hrpf;
     private BigDecimal hrje;
     private BigDecimal fa;
     private Set sweFtecnXsols = new HashSet(0);
     private Set sweFactAmbiXsols = new HashSet(0);
     private Set sweCompXsolis = new HashSet(0);
     private Set sweEtapaXsols = new HashSet(0);
     private Set swePronosticos = new HashSet(0);

    public SweSoli() {
    }

	
    public SweSoli(int idEstimacion, SweCata sweCataByIdEstado, SweCata sweCataByIdAplicacion, SweCata sweCataByIdTposolicitud, SweCata sweCataByIdLenguaje, SweCata sweCataByIdPerfil, SweUsuarios sweUsuariosByIdUsu_estima, int numSolicitud, BigDecimal upf, BigDecimal vaf, BigDecimal apf, BigDecimal fce, BigDecimal he, int ct, BigDecimal tpf, BigDecimal hepf, BigDecimal fa) {
        this.idEstimacion = idEstimacion;
        this.sweCataByIdEstado = sweCataByIdEstado;
        this.sweCataByIdAplicacion = sweCataByIdAplicacion;
        this.sweCataByIdTposolicitud = sweCataByIdTposolicitud;
        this.sweCataByIdLenguaje = sweCataByIdLenguaje;
        this.sweCataByIdPerfil = sweCataByIdPerfil;
        this.sweUsuariosByIdUsu_estima = sweUsuariosByIdUsu_estima;
        this.numSolicitud = numSolicitud;
        this.upf = upf;
        this.vaf = vaf;
        this.apf = apf;
        this.fce = fce;
        this.he = he;
        this.ct = ct;
        this.tpf = tpf;
        this.hepf = hepf;
        this.fa = fa;
    }
    public SweSoli(int idEstimacion, SweCata sweCataByIdEstado, SweCata sweCataByIdAplicacion, SweCata sweCataByIdTposolicitud, SweCata sweCataByIdLenguaje, SweCata sweCataByIdPerfil, SweUsuarios sweUsuariosByIdUsu_estima, SweUsuarios sweUsuariosByIdUsu_cierra,int numSolicitud, String descripcion, String aprobada, Date fechaModificacion, Date fechaAprobacion, BigDecimal upf, BigDecimal vaf, BigDecimal apf, BigDecimal fce, BigDecimal fcr, BigDecimal he, BigDecimal hr, int ct, BigDecimal tpf, BigDecimal hepf, BigDecimal hrpf, BigDecimal hrje, BigDecimal fa, Set sweFtecnXsols, Set sweFactAmbiXsols, Set sweCompXsolis, Set sweEtapaXsols, Set swePronosticos) {
       this.idEstimacion = idEstimacion;
       this.sweCataByIdEstado = sweCataByIdEstado;
       this.sweCataByIdAplicacion = sweCataByIdAplicacion;
       this.sweCataByIdTposolicitud = sweCataByIdTposolicitud;
       this.sweCataByIdLenguaje = sweCataByIdLenguaje;
       this.sweCataByIdPerfil = sweCataByIdPerfil;
       this.sweUsuariosByIdUsu_estima = sweUsuariosByIdUsu_estima;
       this.sweUsuariosByIdUsu_cierra = sweUsuariosByIdUsu_cierra;
       this.numSolicitud = numSolicitud;
       this.descripcion = descripcion;
       this.aprobada = aprobada;
       this.fechaModificacion = fechaModificacion;
       this.fechaAprobacion = fechaAprobacion;
       this.upf = upf;
       this.vaf = vaf;
       this.apf = apf;
       this.fce = fce;
       this.fcr = fcr;
       this.he = he;
       this.hr = hr;
       this.ct = ct;
       this.tpf = tpf;
       this.hepf = hepf;
       this.hrpf = hrpf;
       this.hrje = hrje;
       this.fa = fa;
       this.sweFtecnXsols = sweFtecnXsols;
       this.sweFactAmbiXsols = sweFactAmbiXsols;
       this.sweCompXsolis = sweCompXsolis;
       this.sweEtapaXsols = sweEtapaXsols;
       this.swePronosticos = swePronosticos;
    }
   
    public int getIdEstimacion() {
        return this.idEstimacion;
    }
    
    public void setIdEstimacion(int idEstimacion) {
        this.idEstimacion = idEstimacion;
    }
    public SweCata getSweCataByIdEstado() {
        return this.sweCataByIdEstado;
    }
    
    public void setSweCataByIdEstado(SweCata sweCataByIdEstado) {
        this.sweCataByIdEstado = sweCataByIdEstado;
    }
    public SweCata getSweCataByIdAplicacion() {
        return this.sweCataByIdAplicacion;
    }
    
    public void setSweCataByIdAplicacion(SweCata sweCataByIdAplicacion) {
        this.sweCataByIdAplicacion = sweCataByIdAplicacion;
    }
    public SweCata getSweCataByIdTposolicitud() {
        return this.sweCataByIdTposolicitud;
    }
    
    public void setSweCataByIdTposolicitud(SweCata sweCataByIdTposolicitud) {
        this.sweCataByIdTposolicitud = sweCataByIdTposolicitud;
    }
    public SweCata getSweCataByIdLenguaje() {
        return this.sweCataByIdLenguaje;
    }
    
    public void setSweCataByIdLenguaje(SweCata sweCataByIdLenguaje) {
        this.sweCataByIdLenguaje = sweCataByIdLenguaje;
    }
    public SweCata getSweCataByIdPerfil() {
        return this.sweCataByIdPerfil;
    }
    
    public void setSweCataByIdPerfil(SweCata sweCataByIdPerfil) {
        this.sweCataByIdPerfil = sweCataByIdPerfil;
    }
    public int getNumSolicitud() {
        return this.numSolicitud;
    }
    
    public void setNumSolicitud(int numSolicitud) {
        this.numSolicitud = numSolicitud;
    }
    
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Date getFechaAprobacion() {
        return this.fechaAprobacion;
    }
    
    public void setFechaAprobacion(Date fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }
    public BigDecimal getUpf() {
        return this.upf;
    }
    
    public void setUpf(BigDecimal upf) {
        this.upf = upf;
    }
    public BigDecimal getVaf() {
        return this.vaf;
    }
    
    public void setVaf(BigDecimal vaf) {
        this.vaf = vaf;
    }
    public BigDecimal getApf() {
        return this.apf;
    }
    
    public void setApf(BigDecimal apf) {
        this.apf = apf;
    }
    public BigDecimal getFce() {
        return this.fce;
    }
    
    public void setFce(BigDecimal fce) {
        this.fce = fce;
    }
    public BigDecimal getFcr() {
        return this.fcr;
    }
    
    public void setFcr(BigDecimal fcr) {
        this.fcr = fcr;
    }
    public BigDecimal getHe() {
        return this.he;
    }
    
    public void setHe(BigDecimal he) {
        this.he = he;
    }
    public BigDecimal getHr() {
        return this.hr;
    }
    
    public void setHr(BigDecimal hr) {
        this.hr = hr;
    }
    public int getCt() {
        return this.ct;
    }
    
    public void setCt(int ct) {
        this.ct = ct;
    }
    public BigDecimal getTpf() {
        return this.tpf;
    }
    
    public void setTpf(BigDecimal tpf) {
        this.tpf = tpf;
    }
    public BigDecimal getHepf() {
        return this.hepf;
    }
    
    public void setHepf(BigDecimal hepf) {
        this.hepf = hepf;
    }
    public BigDecimal getHrpf() {
        return this.hrpf;
    }
    
    public void setHrpf(BigDecimal hrpf) {
        this.hrpf = hrpf;
    }
    public BigDecimal getHrje() {
        return this.hrje;
    }
    
    public void setHrje(BigDecimal hrje) {
        this.hrje = hrje;
    }
    public BigDecimal getFa() {
        return this.fa;
    }
    
    public void setFa(BigDecimal fa) {
        this.fa = fa;
    }
    public Set getSweFtecnXsols() {
        return this.sweFtecnXsols;
    }
    
    public void setSweFtecnXsols(Set sweFtecnXsols) {
        this.sweFtecnXsols = sweFtecnXsols;
    }
    public Set getSweFactAmbiXsols() {
        return this.sweFactAmbiXsols;
    }
    
    public void setSweFactAmbiXsols(Set sweFactAmbiXsols) {
        this.sweFactAmbiXsols = sweFactAmbiXsols;
    }
    public Set getSweCompXsolis() {
        return this.sweCompXsolis;
    }
    
    public void setSweCompXsolis(Set sweCompXsolis) {
        this.sweCompXsolis = sweCompXsolis;
    }
    public Set getSweEtapaXsols() {
        return this.sweEtapaXsols;
    }
    
    public void setSweEtapaXsols(Set sweEtapaXsols) {
        this.sweEtapaXsols = sweEtapaXsols;
    }

    /**
     * @return the fechaCreacion
     */
    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    /**
     * @param fechaCreacion the fechaCreacion to set
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * @return the descripcion
     */
    public String getDescripcion() {
        return descripcion;
    }

    /**
     * @param descripcion the descripcion to set
     */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    /**
     * @return the aprobada
     */
    public String getAprobada() {
        return aprobada;
    }

    /**
     * @param aprobada the aprobada to set
     */
    public void setAprobada(String aprobada) {
        this.aprobada = aprobada;
    }

    /**
     * @return the sweUsuariosByIdUsu_estima
     */
    public SweUsuarios getSweUsuariosByIdUsu_estima() {
        return sweUsuariosByIdUsu_estima;
    }

    /**
     * @param sweUsuariosByIdUsu_estima the sweUsuariosByIdUsu_estima to set
     */
    public void setSweUsuariosByIdUsu_estima(SweUsuarios sweUsuariosByIdUsu_estima) {
        this.sweUsuariosByIdUsu_estima = sweUsuariosByIdUsu_estima;
    }

    /**
     * @return the sweUsuariosByIdUsu_cierra
     */
    public SweUsuarios getSweUsuariosByIdUsu_cierra() {
        return sweUsuariosByIdUsu_cierra;
    }

    /**
     * @param sweUsuariosByIdUsu_cierra the sweUsuariosByIdUsu_cierra to set
     */
    public void setSweUsuariosByIdUsu_cierra(SweUsuarios sweUsuariosByIdUsu_cierra) {
        this.sweUsuariosByIdUsu_cierra = sweUsuariosByIdUsu_cierra;
    }

    /**
     * @return the swePronosticos
     */
    public Set getSwePronosticos() {
        return swePronosticos;
    }

    /**
     * @param swePronosticos the swePronosticos to set
     */
    public void setSwePronosticos(Set swePronosticos) {
        this.swePronosticos = swePronosticos;
    }

}


