package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SweTipoDetret generated by hbm2java
 */
public class SweTipoDetret  implements java.io.Serializable {


     private int codigoTipoDetret;
     private String nombre;
     private String descripcion;
     private Set sweCataDetrets = new HashSet(0);

    public SweTipoDetret() {
    }

	
    public SweTipoDetret(int codigoTipoDetret, String nombre, String descripcion) {
        this.codigoTipoDetret = codigoTipoDetret;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public SweTipoDetret(int codigoTipoDetret, String nombre, String descripcion, Set sweCataDetrets) {
       this.codigoTipoDetret = codigoTipoDetret;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.sweCataDetrets = sweCataDetrets;
    }
   
    public int getCodigoTipoDetret() {
        return this.codigoTipoDetret;
    }
    
    public void setCodigoTipoDetret(int codigoTipoDetret) {
        this.codigoTipoDetret = codigoTipoDetret;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSweCataDetrets() {
        return this.sweCataDetrets;
    }
    
    public void setSweCataDetrets(Set sweCataDetrets) {
        this.sweCataDetrets = sweCataDetrets;
    }




}


