package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA



/**
 * SweTipoApliXFtec generated by hbm2java
 */
public class SweTipoApliXFtec  implements java.io.Serializable {


     private SweTipoApliXFtecId id;
     private SweCata sweCataByCodigoTpoaplicacion;
     private SweCata sweCataByCodigoFacttecnico;
     private int gradoInfluencia;

    public SweTipoApliXFtec() {
    }

    public SweTipoApliXFtec(SweTipoApliXFtecId id, SweCata sweCataByCodigoTpoaplicacion, SweCata sweCataByCodigoFacttecnico, int gradoInfluencia) {
       this.id = id;
       this.sweCataByCodigoTpoaplicacion = sweCataByCodigoTpoaplicacion;
       this.sweCataByCodigoFacttecnico = sweCataByCodigoFacttecnico;
       this.gradoInfluencia = gradoInfluencia;
    }
   
    public SweTipoApliXFtecId getId() {
        return this.id;
    }
    
    public void setId(SweTipoApliXFtecId id) {
        this.id = id;
    }
    public SweCata getSweCataByCodigoTpoaplicacion() {
        return this.sweCataByCodigoTpoaplicacion;
    }
    
    public void setSweCataByCodigoTpoaplicacion(SweCata sweCataByCodigoTpoaplicacion) {
        this.sweCataByCodigoTpoaplicacion = sweCataByCodigoTpoaplicacion;
    }
    public SweCata getSweCataByCodigoFacttecnico() {
        return this.sweCataByCodigoFacttecnico;
    }
    
    public void setSweCataByCodigoFacttecnico(SweCata sweCataByCodigoFacttecnico) {
        this.sweCataByCodigoFacttecnico = sweCataByCodigoFacttecnico;
    }
    public int getGradoInfluencia() {
        return this.gradoInfluencia;
    }
    
    public void setGradoInfluencia(int gradoInfluencia) {
        this.gradoInfluencia = gradoInfluencia;
    }




}


