package com.amerika.swe.model;
// Generated 18/09/2013 08:04:33 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SweTcompXComp generated by hbm2java
 */
public class SweTcompXComp  implements java.io.Serializable {


    private int idTcomxcomp;
    private SweCata sweCataByIdTpocomplejidad;
    private SweCata sweCataByIdTpocomponente;
    private int peso;
    private Date vigenciaInicial;
    private Date vigenciaFinal;

    public SweTcompXComp() {
    }

	
    public SweTcompXComp(int idTcomxcomp, SweCata sweCataByIdTpocomplejidad, SweCata sweCataByIdTpocomponente, int peso, Date vigenciaInicial) {
        this.idTcomxcomp = idTcomxcomp;
        this.sweCataByIdTpocomplejidad = sweCataByIdTpocomplejidad;
        this.sweCataByIdTpocomponente = sweCataByIdTpocomponente;
        this.peso = peso;
        this.vigenciaInicial = vigenciaInicial;
    }
    public SweTcompXComp(int idTcomxcomp, SweCata sweCataByIdTpocomplejidad, SweCata sweCataByIdTpocomponente, int peso, Date vigenciaInicial, Date vigenciaFinal) {
       this.idTcomxcomp = idTcomxcomp;
       this.sweCataByIdTpocomplejidad = sweCataByIdTpocomplejidad;
       this.sweCataByIdTpocomponente = sweCataByIdTpocomponente;
       this.peso = peso;
       this.vigenciaInicial = vigenciaInicial;
       this.vigenciaFinal = vigenciaFinal;
    }
   
    public int getIdTcomxcomp() {
        return this.idTcomxcomp;
    }
    
    public void setIdTcomxcomp(int idTcomxcomp) {
        this.idTcomxcomp = idTcomxcomp;
    }
    public SweCata getSweCataByIdTpocomplejidad() {
        return this.sweCataByIdTpocomplejidad;
    }
    
    public void setSweCataByIdTpocomplejidad(SweCata sweCataByIdTpocomplejidad) {
        this.sweCataByIdTpocomplejidad = sweCataByIdTpocomplejidad;
    }
    public SweCata getSweCataByIdTpocomponente() {
        return this.sweCataByIdTpocomponente;
    }
    
    public void setSweCataByIdTpocomponente(SweCata sweCataByIdTpocomponente) {
        this.sweCataByIdTpocomponente = sweCataByIdTpocomponente;
    }
    public int getPeso() {
        return this.peso;
    }
    
    public void setPeso(int peso) {
        this.peso = peso;
    }
    public Date getVigenciaInicial() {
        return this.vigenciaInicial;
    }
    
    public void setVigenciaInicial(Date vigenciaInicial) {
        this.vigenciaInicial = vigenciaInicial;
    }
    public Date getVigenciaFinal() {
        return this.vigenciaFinal;
    }
    
    public void setVigenciaFinal(Date vigenciaFinal) {
        this.vigenciaFinal = vigenciaFinal;
    }

}


