package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA



/**
 * SweTipoApliXFtecId generated by hbm2java
 */
public class SweTipoApliXFtecId  implements java.io.Serializable {


     private int codigoFacttecnico;
     private int codigoTpoaplicacion;

    public SweTipoApliXFtecId() {
    }

    public SweTipoApliXFtecId(int codigoFacttecnico, int codigoTpoaplicacion) {
       this.codigoFacttecnico = codigoFacttecnico;
       this.codigoTpoaplicacion = codigoTpoaplicacion;
    }
   
    public int getCodigoFacttecnico() {
        return this.codigoFacttecnico;
    }
    
    public void setCodigoFacttecnico(int codigoFacttecnico) {
        this.codigoFacttecnico = codigoFacttecnico;
    }
    public int getCodigoTpoaplicacion() {
        return this.codigoTpoaplicacion;
    }
    
    public void setCodigoTpoaplicacion(int codigoTpoaplicacion) {
        this.codigoTpoaplicacion = codigoTpoaplicacion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SweTipoApliXFtecId) ) return false;
		 SweTipoApliXFtecId castOther = ( SweTipoApliXFtecId ) other; 
         
		 return (this.getCodigoFacttecnico()==castOther.getCodigoFacttecnico())
 && (this.getCodigoTpoaplicacion()==castOther.getCodigoTpoaplicacion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigoFacttecnico();
         result = 37 * result + this.getCodigoTpoaplicacion();
         return result;
   }   


}


