package com.amerika.swe.model;
// Generated 10/09/2013 09:52:41 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SweTipoCata generated by hbm2java
 */
public class SweTipoCata  implements java.io.Serializable {


    private int codigoTipo;
    private String nombre;
    private String descripcion;
    private String mostrarEstado;
    private String mostrarValor;
    private String estado;
    private Set sweCatas = new HashSet(0);

    public SweTipoCata() {
    }

	
    public SweTipoCata(int codigoTipo, String nombre, String descripcion, String mostrarEstado, String mostrarValor, String estado) {
        this.codigoTipo = codigoTipo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.mostrarEstado = mostrarEstado;
        this.mostrarValor = mostrarValor;
        this.estado = estado;
    }
    public SweTipoCata(int codigoTipo, String nombre, String descripcion, String mostrarEstado, String mostrarValor, String estado,Set sweCatas) {
       this.codigoTipo = codigoTipo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.mostrarEstado = mostrarEstado;
       this.mostrarValor = mostrarValor;
       this.sweCatas = sweCatas;
       this.estado = estado;
    }
   
    public int getCodigoTipo() {
        return this.codigoTipo;
    }
    
    public void setCodigoTipo(int codigoTipo) {
        this.codigoTipo = codigoTipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getMostrarEstado() {
        return this.mostrarEstado;
    }
    
    public void setMostrarEstado(String mostrarEstado) {
        this.mostrarEstado = mostrarEstado;
    }
    public String getMostrarValor() {
        return this.mostrarValor;
    }
    
    public void setMostrarValor(String mostrarValor) {
        this.mostrarValor = mostrarValor;
    }
    public Set getSweCatas() {
        return this.sweCatas;
    }
    
    public void setSweCatas(Set sweCatas) {
        this.sweCatas = sweCatas;
    }

    /**
     * @return the estado
     */
    public String getEstado() {
        return estado;
    }

    /**
     * @param estado the estado to set
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

}